ucb_site_configuration.external_service_include.add:
  route_name: entity.ucb_external_service_include.add_form
  title: Include a third-party service
  appears_on:
    - entity.ucb_external_service_include.collection
