service-livechat:
  version: '1.0'
  js:
    js/service-livechat.js: {}

service-mainstay:
  version: '1.0'
  css:
    theme:
      https://webbot.mainstay.com/static/css/webchat.css: { type: external }
  js:
    js/service-mainstay.js: {}

service-servicecloud:
  version: '1.0'
  css:
    theme:
      css/service-servicecloud.css: {}
  js:
    js/service-servicecloud.js: {}

service-statuspage:
  version: '1.0'
  js:
    js/service-statuspage.js: {}

service-goodkind:
  version: '1.0'
  js:
    js/service-goodkind.js: {}

service-salesforce:
  version: '1.0'
  js:
    js/service-salesforce.js: {}
